# Generated by Django 4.2.3 on 2023-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'AdminDetails',
            },
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100, null=True)),
                ('Password', models.CharField(default=None, max_length=100, null=True)),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('Age', models.CharField(default=None, max_length=200, null=True)),
                ('Phone', models.CharField(default=None, max_length=100, null=True)),
                ('Email', models.CharField(default=None, max_length=100, null=True)),
                ('Address', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'userDetails',
            },
        ),
    ]
