# Generated by Django 4.2.3 on 2023-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0002_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=None, max_length=100, null=True)),
                ('Description', models.CharField(default=None, max_length=400, null=True)),
                ('Image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'Information',
            },
        ),
    ]
