# Generated by Django 4.2.3 on 2023-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0003_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Title',
            new_name='Consultation_Fees',
        ),
        migrations.RemoveField(
            model_name='information',
            name='Description',
        ),
        migrations.AddField(
            model_name='information',
            name='Consultation_Hours',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Gender',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Languages_Spoken',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Profile_Picture',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Qualifications',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Specialization',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Venue',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Years',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
