# Generated by Django 4.2.3 on 2023-07-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0004_rename_title_information_consultation_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Age',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
