# Generated by Django 4.2.3 on 2023-07-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0005_information_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='Profile_Picture',
        ),
    ]
