# Generated by Django 4.2.3 on 2023-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0008_rename_breakfast_breakfast_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default=None, max_length=100, null=True)),
                ('Food1', models.CharField(default=None, max_length=100, null=True)),
                ('Food2', models.CharField(default=None, max_length=100, null=True)),
                ('Food3', models.CharField(default=None, max_length=100, null=True)),
                ('Food4', models.CharField(default=None, max_length=100, null=True)),
                ('Food5', models.CharField(default=None, max_length=100, null=True)),
                ('Food6', models.CharField(default=None, max_length=100, null=True)),
                ('Food7', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Lunch_List',
            },
        ),
    ]
