# Generated by Django 4.2.3 on 2023-07-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0011_dinner_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_list',
            name='Food1',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food3',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food4',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food5',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food6',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='Food7',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dinner_list',
            name='userid',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
