# Generated by Django 4.2.4 on 2023-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet_App', '0012_alter_dinner_list_food1_alter_dinner_list_food2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=200, null=True)),
                ('Age', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Example_table',
            },
        ),
    ]
